### ISSUE TITLE
Make it Python 3.x compatible

### ISSUE THREAD

**Issue by RayeN** [yola/yoconfigurator#34]
We'll need it for our new project (which will be run under Python 3.x)

**Comment by jamesodo** [comment]
We only need to support 2.7 and 3.5?

**Comment by stefanor** [comment]
`>= 3.5`, please.

And `>= 3.0` if there is no reason to avoid it. 3.2 will certainly be useful, as it's the python3 on precise.

**Comment by jamesodo** [comment]
>     >= 3.5, please.
>     And >= 3.0

Did you >= 2.5 and >= 3.0?
What is still on 2.5?

**Comment by stefanor** [comment]
I didn't say 2.5 anywhere.

**Comment by thomasw** [comment]
Except for just then.

**Comment by adrianmoisey** [comment]
You guys 😂

**Comment by snitch** [comment]
@jamesodo: This issue is now a priority.
